#!/bin/sh
opts="-zero=f -h=600 -xlabel=10 -yrange=-1,1,0.25 -yfmt=%0.2f -grid"
./echart $opts -area                                                   sin.d &
./echart $opts -bar                                                    sin.d &
./echart $opts -line                                                   sin.d &
./echart $opts -scatter                                                sin.d &
./echart $opts -area -line                                             sin.d &
./echart $opts -area -bar -line -scatter -frame 20                     sin.d &

./echart -xlabel=5 -scatter -vfmt=%.2f -yrange=0,100,10 -grid          rand.d &
./echart -textsize=2 -dot -dotsize=1                                   data.d &

opts="-ls=5 -textsize=3 -yrange=0,100,20 -grid"
./echart $opts -hbar  -barwidth=2                                      data.d &
./echart $opts -wbar                                                   data.d &

opts="-left=30"
./echart $opts -top 75 -left 15 -piesize 30   -pie                     browser.d &
./echart $opts -dotsize 5 -lego                                        pop.d &
